-- =====================================================================================
-- FORGE SEED DATA
-- Auto-generated from packages/shared/src/constants.ts
-- =====================================================================================

INSERT INTO public.exercises (id, nom, tier_snc, muscle_primaire, muscles_secondaires, equipment, tension_matrix) VALUES
('squat', 'Squat Arrière', 1, 'quadriceps', ARRAY['gluteal', 'hamstring', 'lowerBack']::text[], 'poids_libre', '{"quadriceps":1,"gluteal":0.7,"lowerBack":0.4,"hamstring":0.15}'::jsonb),
('deadlift', 'Soulevé de Terre', 1, 'lowerBack', ARRAY['gluteal', 'hamstring', 'trapezius', 'forearm', 'upperBack']::text[], 'poids_libre', '{"lowerBack":1,"gluteal":0.8,"hamstring":0.85,"trapezius":0.5,"forearm":0.4,"upperBack":0.3}'::jsonb),
('bench_press', 'Développé Couché', 2, 'chest', ARRAY['frontDeltoid', 'triceps']::text[], 'poids_libre', '{"chest":1,"frontDeltoid":0.6,"triceps":0.5}'::jsonb),
('ohp', 'Overhead Press (OHP)', 1, 'frontDeltoid', ARRAY['triceps', 'trapezius']::text[], 'poids_libre', '{"frontDeltoid":1,"triceps":0.5,"trapezius":0.3}'::jsonb),
('pull_ups', 'Tractions', 2, 'upperBack', ARRAY['biceps', 'forearm', 'trapezius']::text[], 'pdc', '{"upperBack":1,"biceps":0.6,"forearm":0.4,"trapezius":0.2}'::jsonb),
('barbell_row', 'Rowing Barre', 1, 'upperBack', ARRAY['trapezius', 'biceps', 'lowerBack', 'forearm']::text[], 'poids_libre', '{"upperBack":1,"trapezius":0.6,"rhomboids":0.6,"biceps":0.5,"lowerBack":0.5,"forearm":0.4}'::jsonb),
('dips', 'Dips', 2, 'chest', ARRAY['triceps', 'frontDeltoid']::text[], 'pdc', '{"lowerChest":0.8,"triceps":0.8,"frontDeltoid":0.5}'::jsonb),
('biceps_curl', 'Curl Biceps (Barre/Haltères)', 3, 'biceps', ARRAY['forearm']::text[], 'poids_libre', '{"biceps":1,"forearm":0.3}'::jsonb),
('triceps_pushdown', 'Extension Triceps Poulie', 3, 'triceps', ARRAY[]::text[], 'machine', '{"triceps":1}'::jsonb),
('incline_bench', 'Développé Incliné', 2, 'chest', ARRAY['frontDeltoid', 'triceps']::text[], 'poids_libre', '{"upperChest":1,"frontDeltoid":0.7,"triceps":0.4}'::jsonb),
('leg_press', 'Presse à Cuisses', 2, 'quadriceps', ARRAY['gluteal']::text[], 'machine', '{"quadriceps":1,"gluteal":0.4}'::jsonb),
('leg_curl', 'Leg Curl', 3, 'hamstring', ARRAY[]::text[], 'machine', '{"hamstring":1}'::jsonb),
('leg_extension', 'Leg Extension', 3, 'quadriceps', ARRAY[]::text[], 'machine', '{"quadriceps":1}'::jsonb),
('lateral_raise', 'Élévations Latérales', 3, 'deltoids', ARRAY[]::text[], 'poids_libre', '{"deltoids":1}'::jsonb),
('face_pull', 'Face Pull', 3, 'rearDeltoid', ARRAY['trapezius']::text[], 'machine', '{"rearDeltoid":1,"trapezius":0.5,"rhomboids":0.6}'::jsonb),
('calf_raise', 'Mollets Debout', 3, 'calves', ARRAY[]::text[], 'poids_libre', '{"calves":1}'::jsonb),
('crunchs', 'Crunchs Abdominaux', 3, 'abs', ARRAY[]::text[], 'pdc', '{"abs":1}'::jsonb),
('plank', 'Planche Gainage', 3, 'abs', ARRAY['obliques', 'lowerBack']::text[], 'pdc', '{"abs":1,"obliques":0.5,"lowerBack":0.3}'::jsonb),
('lunges', 'Fentes Haltères', 2, 'quadriceps', ARRAY['gluteal', 'hamstring']::text[], 'poids_libre', '{"quadriceps":0.8,"gluteal":0.7,"hamstring":0.2}'::jsonb),
('hip_thrust', 'Hip Thrust', 2, 'gluteal', ARRAY['hamstring']::text[], 'poids_libre', '{"gluteal":1,"hamstring":0.3}'::jsonb),
('pec_deck', 'Pec Deck', 3, 'chest', ARRAY[]::text[], 'machine', '{"chest":1}'::jsonb),
('lat_pulldown', 'Tirage Poitrine Poulie', 2, 'upperBack', ARRAY['biceps', 'trapezius', 'forearm']::text[], 'machine', '{"upperBack":1,"biceps":0.5,"trapezius":0.3,"forearm":0.2}'::jsonb),
('flat_db_press', 'Développé Couché Haltères', 2, 'chest', ARRAY['frontDeltoid', 'triceps']::text[], 'poids_libre', '{"chest":1,"frontDeltoid":0.5,"triceps":0.4}'::jsonb),
('incline_db_press', 'Développé Incliné Haltères', 2, 'upperChest', ARRAY['chest', 'frontDeltoid', 'triceps']::text[], 'poids_libre', '{"upperChest":1,"chest":0.3,"frontDeltoid":0.6,"triceps":0.3}'::jsonb),
('cable_fly', 'Écarté Poulie', 3, 'chest', ARRAY['serratus']::text[], 'machine', '{"chest":1,"serratus":0.2}'::jsonb),
('machine_chest_press', 'Développé Machine Assis', 2, 'chest', ARRAY['triceps']::text[], 'machine', '{"chest":1,"triceps":0.4}'::jsonb),
('seated_cable_row', 'Rowing Assis Poulie', 2, 'upperBack', ARRAY['trapezius', 'biceps']::text[], 'machine', '{"upperBack":1,"trapezius":0.4,"biceps":0.4}'::jsonb),
('t_bar_row', 'T-Bar Row', 2, 'upperBack', ARRAY['trapezius', 'lowerBack', 'biceps']::text[], 'poids_libre', '{"upperBack":1,"trapezius":0.5,"lowerBack":0.3,"biceps":0.4}'::jsonb),
('single_arm_db_row', 'Rowing Bûcheron Haltère', 2, 'upperBack', ARRAY['biceps', 'lowerBack']::text[], 'poids_libre', '{"upperBack":1,"biceps":0.5,"lowerBack":0.2}'::jsonb),
('straight_arm_pulldown', 'Pull-over Poulie Haute', 3, 'upperBack', ARRAY['serratus']::text[], 'machine', '{"upperBack":1,"serratus":0.3}'::jsonb),
('pendlay_row', 'Pendlay Row', 1, 'upperBack', ARRAY['trapezius', 'lowerBack']::text[], 'poids_libre', '{"upperBack":1,"trapezius":0.7,"lowerBack":0.3}'::jsonb),
('goblet_squat', 'Goblet Squat', 2, 'quadriceps', ARRAY['gluteal', 'abs']::text[], 'poids_libre', '{"quadriceps":0.9,"gluteal":0.5,"abs":0.2}'::jsonb),
('romanian_deadlift', 'Soulevé de Terre Roumain (RDL)', 1, 'hamstring', ARRAY['gluteal', 'lowerBack']::text[], 'poids_libre', '{"hamstring":1,"gluteal":0.7,"lowerBack":0.4}'::jsonb),
('bulgarian_split_squat', 'Squat Bulgare', 2, 'quadriceps', ARRAY['gluteal']::text[], 'poids_libre', '{"quadriceps":0.9,"gluteal":0.6}'::jsonb),
('seated_leg_curl', 'Leg Curl Assis', 3, 'hamstring', ARRAY[]::text[], 'machine', '{"hamstring":1}'::jsonb),
('leg_extension_unilateral', 'Leg Extension Unilatéral', 3, 'quadriceps', ARRAY[]::text[], 'machine', '{"quadriceps":1}'::jsonb),
('arnold_press', 'Développé Arnold', 2, 'frontDeltoid', ARRAY['triceps', 'upperChest']::text[], 'poids_libre', '{"frontDeltoid":1,"triceps":0.4,"upperChest":0.2}'::jsonb),
('db_lateral_raise', 'Élévations Latérales Haltères', 3, 'deltoids', ARRAY[]::text[], 'poids_libre', '{"deltoids":1}'::jsonb),
('reverse_pec_deck', 'Oiseau Machine (Reverse Pec Deck)', 3, 'rearDeltoid', ARRAY['rhomboids']::text[], 'machine', '{"rearDeltoid":1,"rhomboids":0.4}'::jsonb),
('hammer_curl', 'Curl Marteau', 3, 'biceps', ARRAY['forearm']::text[], 'poids_libre', '{"biceps":0.8,"forearm":0.5}'::jsonb),
('skull_crushers', 'Barre au Front (Skullcrushers)', 3, 'triceps', ARRAY[]::text[], 'poids_libre', '{"triceps":1}'::jsonb),
('hanging_leg_raise', 'Relevé de Jambes Suspendu', 2, 'lowerAbs', ARRAY['upperAbs']::text[], 'pdc', '{"lowerAbs":1,"upperAbs":0.5}'::jsonb),
('ab_wheel_rollout', 'Ab Wheel Rollout', 2, 'abs', ARRAY[]::text[], 'unknown', '{"abs":1,"lowerBack":0.3,"upperBack":0.2}'::jsonb),
('russian_twist', 'Russian Twist', 2, 'obliques', ARRAY[]::text[], 'unknown', '{"obliques":1,"abs":0.5}'::jsonb),
('cable_crunch', 'Cable Crunch', 2, 'abs', ARRAY[]::text[], 'unknown', '{"abs":1}'::jsonb),
('decline_bench_press', 'Decline Bench Press', 2, 'lowerChest', ARRAY[]::text[], 'unknown', '{"lowerChest":1,"triceps":0.5,"frontDeltoid":0.3}'::jsonb),
('db_pullover', 'Db Pullover', 2, 'chest', ARRAY[]::text[], 'unknown', '{"chest":0.8,"upperBack":0.8,"triceps":0.3}'::jsonb),
('machine_fly', 'Machine Fly', 2, 'chest', ARRAY[]::text[], 'unknown', '{"chest":1}'::jsonb),
('push_ups', 'Push Ups', 2, 'chest', ARRAY[]::text[], 'unknown', '{"chest":1,"frontDeltoid":0.5,"triceps":0.6,"abs":0.2}'::jsonb),
('weighted_dips', 'Weighted Dips', 2, 'lowerChest', ARRAY[]::text[], 'unknown', '{"lowerChest":1,"triceps":0.8,"frontDeltoid":0.5}'::jsonb),
('chin_ups', 'Chin Ups', 2, 'upperBack', ARRAY[]::text[], 'unknown', '{"upperBack":0.8,"biceps":1,"forearm":0.4}'::jsonb),
('close_grip_pulldown', 'Close Grip Pulldown', 2, 'upperBack', ARRAY[]::text[], 'unknown', '{"upperBack":1,"biceps":0.7,"forearm":0.3}'::jsonb),
('db_shrugs', 'Db Shrugs', 2, 'upperTrapezius', ARRAY[]::text[], 'unknown', '{"upperTrapezius":1,"forearm":0.5}'::jsonb),
('barbell_shrugs', 'Barbell Shrugs', 2, 'upperTrapezius', ARRAY[]::text[], 'unknown', '{"upperTrapezius":1,"forearm":0.6}'::jsonb),
('machine_row', 'Machine Row', 2, 'upperBack', ARRAY[]::text[], 'unknown', '{"upperBack":1,"biceps":0.4,"rearDeltoid":0.3}'::jsonb),
('good_mornings', 'Good Mornings', 2, 'lowerBack', ARRAY[]::text[], 'unknown', '{"lowerBack":1,"hamstring":0.8,"gluteal":0.5}'::jsonb),
('back_extension', 'Back Extension', 2, 'lowerBack', ARRAY[]::text[], 'unknown', '{"lowerBack":1,"gluteal":0.5,"hamstring":0.3}'::jsonb),
('seated_db_press', 'Seated Db Press', 2, 'frontDeltoid', ARRAY[]::text[], 'unknown', '{"frontDeltoid":1,"triceps":0.4,"upperChest":0.1}'::jsonb),
('front_raise', 'Front Raise', 2, 'frontDeltoid', ARRAY[]::text[], 'unknown', '{"frontDeltoid":1}'::jsonb),
('cable_lateral_raise', 'Cable Lateral Raise', 2, 'deltoids', ARRAY[]::text[], 'unknown', '{"deltoids":1}'::jsonb),
('upright_row', 'Upright Row', 2, 'deltoids', ARRAY[]::text[], 'unknown', '{"deltoids":0.8,"upperTrapezius":0.8,"biceps":0.3}'::jsonb),
('machine_shoulder_press', 'Machine Shoulder Press', 2, 'frontDeltoid', ARRAY[]::text[], 'unknown', '{"frontDeltoid":1,"triceps":0.4}'::jsonb),
('preacher_curl', 'Preacher Curl', 2, 'biceps', ARRAY[]::text[], 'unknown', '{"biceps":1}'::jsonb),
('cable_curl', 'Cable Curl', 2, 'biceps', ARRAY[]::text[], 'unknown', '{"biceps":1,"forearm":0.2}'::jsonb),
('concentration_curl', 'Concentration Curl', 2, 'biceps', ARRAY[]::text[], 'unknown', '{"biceps":1}'::jsonb),
('overhead_triceps_extension', 'Overhead Triceps Extension', 2, 'triceps', ARRAY[]::text[], 'unknown', '{"triceps":1}'::jsonb),
('close_grip_bench_press', 'Close Grip Bench Press', 2, 'triceps', ARRAY[]::text[], 'unknown', '{"triceps":1,"chest":0.6,"frontDeltoid":0.4}'::jsonb),
('french_press', 'French Press', 2, 'triceps', ARRAY[]::text[], 'unknown', '{"triceps":1}'::jsonb),
('front_squat', 'Front Squat', 2, 'quadriceps', ARRAY[]::text[], 'unknown', '{"quadriceps":1,"gluteal":0.4,"lowerBack":0.5,"abs":0.3}'::jsonb),
('hack_squat', 'Hack Squat', 2, 'quadriceps', ARRAY[]::text[], 'unknown', '{"quadriceps":1,"gluteal":0.5}'::jsonb),
('sumo_deadlift', 'Sumo Deadlift', 2, 'gluteal', ARRAY[]::text[], 'unknown', '{"gluteal":1,"quadriceps":0.8,"lowerBack":0.6,"hamstring":0.6,"trapezius":0.4}'::jsonb),
('leg_press_45', 'Leg Press 45', 2, 'quadriceps', ARRAY[]::text[], 'unknown', '{"quadriceps":1,"gluteal":0.5}'::jsonb),
('seated_calf_raise', 'Seated Calf Raise', 2, 'calves', ARRAY[]::text[], 'unknown', '{"calves":1}'::jsonb),
('standing_calf_raise', 'Standing Calf Raise', 2, 'calves', ARRAY[]::text[], 'unknown', '{"calves":1}'::jsonb);
